script: |
  super -s -c 'from input.sup
               | join (values {x:3,y:"a"}, {x:4,y:"b"}) using (y)
               | values left'

inputs:
  - name: input.sup
    data: |
      {x:1,y:"a"}
      {x:2,y:"b"}

outputs:
  - name: stdout
    data: |
      {x:1,y:"a"}
      {x:2,y:"b"}
