[book]
authors = ["Steven McCanne",  "Matthew Nibecker", "Phil Rzewski", "Noah Treuhaft"]
language = "en"
src = "src"
title = "SuperDB"

[output.html.fold]
enable = true

[output.html]
additional-css = ["super-example/super-example.css", "copy-button/copy-button.css"]
additional-js = ["super-example.bundle.js", "copy-button/copy-button.js"]
git-repository-url = "https://github.com/brimdata/super/tree/main/book"
no-section-label = true

[output.html.playground]
# Suppress mdBook's copy button since we add our own.
copyable = false
